const $=id=>document.getElementById(id);
const state={busy:false,trace:localStorage.getItem('k-trace')!=='dialogue',lastSeq:0,initialized:false,queueTimer:null};
const labels={'kk-fk-gateway.service':'FK','kk-fk-audit-witness.service':'Audit','kk-k-model-gateway.service':'Model'};
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function cleanSummary(raw){if(!raw)return'';try{const x=JSON.parse(raw);if(x&&typeof x==='object')return Object.entries(x).map(([k,v])=>`${k}: ${String(v)}`).join(' · ')}catch(_e){}return raw}
function classEvent(e){if(e.subject==='human_chat'||e.subject==='human_ask'||e.subject==='human_plan'||e.subject==='human_remember')return'user';if(e.subject==='k_reply')return'k';if(e.subject==='dialogue_error')return'error';if(e.kind==='EXECUTION')return'execution';return'step'}
function eventNode(e){const type=classEvent(e);if(type==='user'||type==='k'){const t=el('article',`turn ${type}`);t.dataset.seq=e.sequence??'';t.append(el('div','who',type==='user'?'YOU':'K'));t.append(el('div','text',e.summary||''));return t}const s=el('div',`step ${type}`);s.dataset.seq=e.sequence??'';const h=el('div','step-head');h.append(el('b','',e.subject||e.kind||'STEP'),el('span','',`#${e.sequence??'—'}`));s.append(h);const summary=cleanSummary(e.summary||'');if(summary)s.append(el('code','',summary));return s}
function renderStream(events){const list=events||[],box=$('stream');if(!state.initialized){box.replaceChildren();for(const e of list)box.append(eventNode(e));state.lastSeq=Math.max(0,...list.map(x=>Number(x.sequence)||0));state.initialized=true;$('emptyState').classList.toggle('hidden',list.length>0);requestAnimationFrame(()=>box.scrollTop=box.scrollHeight);return}const fresh=list.filter(x=>(Number(x.sequence)||0)>state.lastSeq);if(!fresh.length)return;state.lastSeq=Math.max(state.lastSeq,...fresh.map(x=>Number(x.sequence)||0));fresh.forEach((e,i)=>setTimeout(()=>{box.append(eventNode(e));while(box.children.length>100)box.firstElementChild?.remove();$('emptyState').classList.add('hidden');box.scrollTop=box.scrollHeight},Math.min(i*260,1560)))}
function renderStatus(d){const box=$('statusRows');box.replaceChildren();const svc=Object.fromEntries((d.services||[]).map(s=>[s.name,s]));const rows=[['K',!/FAIL|BLOCK|ERROR/i.test(d.k_status||''),'正常'],['F',d.f_status==='ACCEPTED','正常'],['FK',svc['kk-fk-gateway.service']?.ok===true,'正常'],['Audit',svc['kk-fk-audit-witness.service']?.ok===true,'正常'],['Model',svc['kk-k-model-gateway.service']?.ok===true,'正常'],['升级',d.upgrade?.phase!=='UNAVAILABLE',d.upgrade?.phase||'—']];for(const [name,ok,value] of rows){const r=el('div','status-row');const l=el('div','status-name');l.append(el('i','status-dot '+(ok?'ok':'')),el('span','',name));r.append(l,el('span','status-value',ok?value:'异常'));box.append(r)}$('generation').textContent=d.audit?.generation??'—';$('lastRefresh').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});const accepted=d.merge_acceptance==='ACCEPTED'||/ACCEPTED/.test(d.merge_acceptance||'')||/ACCEPTED/.test(d.merge||'');const pill=$('kPill');pill.className='k-pill '+(state.busy?'busy':accepted?'ready':'bad');$('kPillText').textContent=state.busy?'K · 思考中':accepted?'K · 在线':'K · 异常'}
async function refresh(){try{const r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();renderStatus(d);renderStream(d.events||[])}catch(_e){$('kPill').className='k-pill bad';$('kPillText').textContent='K · 连接失败'}}
function autoGrow(){const c=$('composer');c.style.height='auto';c.style.height=Math.min(c.scrollHeight,120)+'px';$('composerWrap').classList.toggle('active',!!c.value);$('composerHint').textContent=c.value?`${new TextEncoder().encode(c.value).length} bytes · Enter 发送 · Shift+Enter 换行`:''}
async function send(){const c=$('composer');const text=c.value.trim();if(!text||state.busy)return;state.busy=true;$('kPill').className='k-pill busy';$('kPillText').textContent='K · 思考中';c.disabled=true;$('inputState').classList.add('busy');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);c.value='';autoGrow();await refresh()}catch(err){$('composerHint').textContent=`发送失败：${err.message}`;$('composerWrap').classList.add('active')}finally{state.busy=false;c.disabled=false;$('inputState').classList.remove('busy');c.focus();await refresh()}}
$('composer').addEventListener('input',autoGrow);$('composer').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send()}});document.addEventListener('keydown',e=>{if(e.target===document.body&&e.key.length===1)$('composer').focus()});
function setTrace(on){state.trace=on;document.body.classList.toggle('dialogue-only',!on);$('traceToggle').textContent=on?'轨迹 · 全部':'轨迹 · 对话';localStorage.setItem('k-trace',on?'all':'dialogue')}$('traceToggle').addEventListener('click',()=>setTrace(!state.trace));setTrace(state.trace);
const drawerContent={root:[['输入方式','页面没有独立输入框。直接键盘输入，Enter 发送，Shift+Enter 换行。'],['运行边界','这里是 K 的认知对话入口；聊天本身不会生成执行授权。'],['显示','右上角可切换完整轨迹 / 只看对话。']],model:[['模型状态','读取 K Model Gateway 的在线状态。'],['API 配置','当前面板不直接显示或泄露任何密钥。']],infra:[['VPS','读取 K/F 服务状态；控制面与面板保持分离。'],['远程入口','Desktop Commander 单 Agent 长期入口独立于本面板。']],tools:[['认知能力','K 当前外部认知能力仍由既有 Files / Search / Remote 工具层治理。'],['执行边界','任何真实动作仍需经过既有 K/F 治理链。']],system:[['自动刷新','状态和审计事件约每 1.5 秒刷新。'],['升级闭环','v0.3 已建立候选生命周期；当前不允许自动安装，安装能力默认关闭。'],['运行模式','面板服务为本机回环地址上的受限服务。']]};
function openDrawer(kind='root'){const title={root:'K 面板',model:'模型与 API',infra:'服务器与基础设施',tools:'工具与能力',system:'系统与运行'}[kind]||'K 面板';$('drawerTitle').textContent=title;const b=$('drawerBody');b.replaceChildren();for(const [h,t] of drawerContent[kind]||drawerContent.root){const c=el('div','drawer-card');c.append(el('b','',h),el('div','',t));b.append(c)}$('drawer').classList.add('open');$('drawer').setAttribute('aria-hidden','false')}
function closeDrawer(){$('drawer').classList.remove('open');$('drawer').setAttribute('aria-hidden','true')}$('orangeRail').addEventListener('click',()=>openDrawer('root'));$('drawerClose').addEventListener('click',closeDrawer);for(const b of document.querySelectorAll('.config-row'))b.addEventListener('click',()=>openDrawer(b.dataset.config));
autoGrow();refresh();setInterval(refresh,1500);setTimeout(()=>$('composer').focus(),250);
