const $=id=>document.getElementById(id);
const MIN_STEP_MS=700;
const MAX_VIDEO_BYTES=500*1024*1024, MAX_VIDEO_SECONDS=600;
const MAX_IMAGE_BYTES=20*1024*1024, MAX_IMAGES=6;
const MAX_FILES=5, MAX_FILE_TOTAL=30*1024*1024, MAX_AUDIO_BYTES=20*1024*1024;
const s={busy:false,settings:false,pressTimer:null,pressStart:0,media:null,stream:null,recording:false,video:false,startTime:0,timer:null,visualQueue:Promise.resolve(),attachments:[],suppressClick:false,chunks:[],permissions:{location:'unknown',motion:'unknown',orientation:'unknown',microphone:'unknown',camera:'unknown'},device:{enabled:false,listeners:false,watchId:null,location:null,motion:null,orientation:null,stability:null}};
const settingsRows=['账户与同步','模型设置','记忆管理','任务管理','工具与连接','设备感知','安装状态','权限状态','显示设置','通知设置','关于'];
const stepNames={ingress:'接收输入',attachment:'接收附件',device:'读取设备感知',history:'读取对话历史',input_commit:'写入本轮输入',identity:'加载 K 身份',self_knowledge:'检查自身知识',capability:'检查能力证据',route:'确定认知路线',deliberation:'进入认知链',soul_a:'生成候选回答',soul_a_retry:'修复候选回答',soul_b:'审查候选回答',soul_c:'裁决候选回答',decision_audit:'写入认知审计',reply_commit:'写入回复审计',complete:'完成'};
function now(){return new Date().toLocaleTimeString([], {hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function isStandalone(){return window.matchMedia?.('(display-mode: standalone)').matches||window.navigator.standalone===true}
function getDeviceIdentity(){let id=localStorage.getItem('kDeviceId');if(!id){const r=crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);id='K-MOBILE-'+r;localStorage.setItem('kDeviceId',id)}const iphone=/iPhone/i.test(navigator.userAgent);return {device_id:id,device_name:iphone?'K iPhone 11':'K Web Terminal',device_model:iphone?'iPhone 11':'Web Device',app_mode:isStandalone()?'standalone':'browser',online:navigator.onLine}}
function permissionSummary(){const p=s.permissions;return `定位:${p.location} · 运动:${p.motion} · 麦克风:${p.microphone} · 摄像头:${p.camera}`}
function renderSettings(){const p=$('settings');p.innerHTML='<div class="settings-title">K 设置</div>'+settingsRows.map(x=>{let attr='',right='›';if(x==='设备感知'){attr='data-device-sense="1"';right=s.device.enabled?'已开启':'开启'}else if(x==='安装状态'){attr='data-install="1"';right=isStandalone()?'已安装':'Safari安装'}else if(x==='权限状态'){attr='data-permissions="1"';right='查看'}return `<div class="setting-row" ${attr}><span>${x}</span><span>${right}</span></div>`}).join('')}
function showInstallHelp(){toast(isStandalone()?'K 已作为主屏幕 App 运行':'Safari 点“分享” → “添加到主屏幕”，以后只从 K 图标进入',5000)}
function showPermissionStatus(){toast(permissionSummary(),5000)}
function openSettings(){s.settings=true;$('settings').classList.add('open');$('settings').setAttribute('aria-hidden','false')}
function setBusy(on){s.busy=on;$('textInput').disabled=on;$('inputState').classList.toggle('busy',on);if(on)closeAttachmentMenu();updateInputState();if(!on)$('progressWrap').classList.add('hidden')}
function openInput(){if(s.busy||s.recording||s.settings)return;$('textInput').focus()}
function closeInput(){$('textInput').blur()}
function scrollBottom(){const t=$('timeline');requestAnimationFrame(()=>{t.scrollTop=t.scrollHeight})}
function fmtDur(ms){if(ms<1000)return Math.max(1,Math.round(ms))+'ms';return (ms/1000).toFixed(ms<10000?1:0)+'s'}
function fmtSize(n){if(n>=1024*1024*1024)return (n/1024/1024/1024).toFixed(1)+'GB';if(n>=1024*1024)return (n/1024/1024).toFixed(1)+'MB';return Math.max(1,Math.round(n/1024))+'KB'}
function nval(v,d=3){return Number.isFinite(v)?Number(v.toFixed(d)):null}
function vec(v){return v?{x:nval(v.x),y:nval(v.y),z:nval(v.z)}:null}
function updateStability(){const m=s.device.motion;if(!m){s.device.stability=null;return}const a=m.acceleration||{},r=m.rotation_rate||{};const amag=Math.hypot(a.x||0,a.y||0,a.z||0),rmag=Math.hypot(r.alpha||0,r.beta||0,r.gamma||0);const index=Math.max(0,Math.min(100,Math.round(100-amag*10-rmag*.35)));s.device.stability={index_0_100:index,state:index>=85?'stable':index>=55?'moving':'active',heuristic:true}}
function onDeviceMotion(e){s.device.motion={interval_ms:nval(e.interval,1),acceleration:vec(e.acceleration),acceleration_including_gravity:vec(e.accelerationIncludingGravity),rotation_rate:e.rotationRate?{alpha:nval(e.rotationRate.alpha),beta:nval(e.rotationRate.beta),gamma:nval(e.rotationRate.gamma)}:null,timestamp_ms:Date.now()};updateStability()}
function onDeviceOrientation(e){s.device.orientation={alpha:nval(e.alpha),beta:nval(e.beta),gamma:nval(e.gamma),absolute:!!e.absolute,compass_heading_deg:nval(e.webkitCompassHeading),compass_accuracy_deg:nval(e.webkitCompassAccuracy),timestamp_ms:Date.now()}}
function startGeo(){if(!navigator.geolocation||s.device.watchId!==null)return;s.device.watchId=navigator.geolocation.watchPosition(p=>{s.permissions.location='granted';const c=p.coords;s.device.location={latitude:nval(c.latitude,6),longitude:nval(c.longitude,6),accuracy_m:nval(c.accuracy,1),altitude_m:nval(c.altitude,1),altitude_accuracy_m:nval(c.altitudeAccuracy,1),heading_deg:nval(c.heading,1),speed_mps:nval(c.speed,2),timestamp_ms:p.timestamp||Date.now()};renderSettings()},e=>{s.permissions.location=e?.code===1?'denied':'unavailable';renderSettings()}, {enableHighAccuracy:true,maximumAge:5000,timeout:12000})}
async function enableDeviceSense(silent=false){try{let mg='granted',og='granted';if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function')mg=await DeviceMotionEvent.requestPermission();if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function')og=await DeviceOrientationEvent.requestPermission();s.permissions.motion=mg==='granted'?'granted':'denied';s.permissions.orientation=og==='granted'?'granted':'denied';if(mg!=='granted'&&og!=='granted')throw new Error('运动与方向权限未允许');if(!s.device.listeners){if(mg==='granted')window.addEventListener('devicemotion',onDeviceMotion,{passive:true});if(og==='granted')window.addEventListener('deviceorientation',onDeviceOrientation,{passive:true});s.device.listeners=true}startGeo();s.device.enabled=true;localStorage.setItem('kDeviceSense','1');renderSettings();if(!silent)toast('设备感知已开启：定位 · 陀螺仪 · 加速度',2600)}catch(e){if(!silent)toast(e.message||'设备感知权限未开启',3000)}}
function deviceSnapshot(){return {schema:'K.DEVICE.SNAPSHOT.1',captured_at_ms:Date.now(),terminal:getDeviceIdentity(),location:s.device.enabled?s.device.location:null,orientation:s.device.enabled?s.device.orientation:null,motion:s.device.enabled?s.device.motion:null,stability:s.device.enabled?s.device.stability:null}}
const STEP_FLOW=['ingress','attachment','history','input_commit','identity','self_knowledge','capability','deliberation','route','soul_a','soul_a_retry','soul_b','soul_c','decision_audit','reply_commit','complete'];
function stepColor(code){const i=STEP_FLOW.indexOf(code),t=i<0?.5:i/(STEP_FLOW.length-1),a=[16,141,255],b=[34,181,115];return `rgb(${a.map((v,j)=>Math.round(v+(b[j]-v)*t)).join(',')})`}
function attachmentLabel(){return s.attachments.map(a=>a.type==='image'?'图片':a.type==='video'?'视频':a.type==='audio'?'录音':a.name).join(' · ')}
function beginTurn(text,label=''){
 const block=document.createElement('section');block.className='turn-block';
 const head=document.createElement('div');head.className='turn-query';const shown=[text,label].filter(Boolean).join('  ');head.innerHTML=`<span>${shown.replace(/</g,'&lt;').replace(/>/g,'&gt;')}</span><time>${now()}</time>`;
 const steps=document.createElement('div');steps.className='turn-steps';const answer=document.createElement('div');answer.className='turn-answer hidden';
 block.append(head,steps,answer);$('timeline').append(block);scrollBottom();return {block,steps,answer,open:new Map(),mono:new Map()};
}
function createStep(turn,ev){const n=document.createElement('div');n.className='step active';n.dataset.code=ev.code||'event';n.style.setProperty('--step-color',stepColor(ev.code));const title=document.createElement('div');title.className='step-title';title.textContent=stepNames[ev.code]||ev.code||'执行步骤';const sub=document.createElement('div');sub.className='step-sub';sub.textContent=ev.detail||'正在处理…';const tm=document.createElement('div');tm.className='step-time';tm.textContent=now();n.append(title,sub,tm);turn.steps.append(n);scrollBottom();turn.open.set(ev.code,n);turn.mono.set(ev.code,{ui:Date.now(),backend:typeof ev.mono==='number'?ev.mono:null});return n}
async function renderProgress(turn,ev){if(ev.state==='START'){createStep(turn,ev);return}let n=turn.open.get(ev.code),meta=turn.mono.get(ev.code);if(!n){n=createStep(turn,{...ev,state:'START'});meta=turn.mono.get(ev.code)}const wait=Math.max(0,MIN_STEP_MS-(Date.now()-meta.ui));if(wait)await sleep(wait);n.classList.remove('active');n.classList.add('done');const sub=n.querySelector('.step-sub');if(ev.detail)sub.textContent=ev.detail;let dur='';if(meta.backend!==null&&typeof ev.mono==='number')dur=' · '+fmtDur(Math.max(0,(ev.mono-meta.backend)*1000));n.querySelector('.step-time').textContent=now()+dur;turn.open.delete(ev.code);turn.mono.delete(ev.code);scrollBottom()}
function queueProgress(turn,ev){s.visualQueue=s.visualQueue.then(()=>renderProgress(turn,ev));return s.visualQueue}
function failTurn(turn,text){const n=document.createElement('div');n.className='step failed';n.innerHTML=`<div class="step-title">处理失败</div><div class="step-sub"></div><div class="step-time">${now()}</div>`;n.querySelector('.step-sub').textContent=text||'未知错误';turn.steps.append(n);scrollBottom()}
function finishTurn(turn,answer){turn.answer.textContent=answer||'';turn.answer.classList.remove('hidden');scrollBottom()}
async function pollRun(runId,turn){let after=-1;while(true){const r=await fetch(`/api/chat/events?run_id=${encodeURIComponent(runId)}&after=${after}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);for(const ev of d.events||[]){after=Math.max(after,ev.seq);queueProgress(turn,ev)}if(d.status!=='RUNNING'){await s.visualQueue;if(d.status==='COMPLETE')finishTurn(turn,d.answer);else failTurn(turn,d.error||d.status||'FAIL');return}await sleep(250)}}
function mediaPayload(){return s.attachments.flatMap(a=>a.media||[])}
async function sendCurrent(){const raw=$('textInput').value.trim(),media=mediaPayload(),device=deviceSnapshot();if((!raw&&!media.length)||s.busy)return;const label=attachmentLabel();const text=raw||'请查看我发送的附件。';setBusy(true);closeInput();const turn=beginTurn(raw,label);$('textInput').value='';autoGrow();s.attachments=[];renderAttachments();try{const r=await fetch('/api/chat/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,media,device})});const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);await pollRun(d.run_id,turn)}catch(e){await s.visualQueue;failTurn(turn,e.message||'发送失败')}finally{setBusy(false)}}
function toast(text,ms=2200){document.querySelector('.toast')?.remove();const n=document.createElement('div');n.className='toast';n.textContent=text;$('stage').append(n);setTimeout(()=>n.remove(),ms)}
function updateInputState(){const ready=!!($('textInput').value.trim()||s.attachments.length);$('inputState').classList.toggle('ready-to-send',ready);$('inputState').setAttribute('aria-label',ready?'发送':'添加图片、视频或文件')}
function openAttachmentMenu(){$('attachmentMenu').classList.add('open');$('attachmentMenu').setAttribute('aria-hidden','false')}
function closeAttachmentMenu(){$('attachmentMenu').classList.remove('open');$('attachmentMenu').setAttribute('aria-hidden','true')}
function toggleAttachmentMenu(){if($('attachmentMenu').classList.contains('open'))closeAttachmentMenu();else openAttachmentMenu()}
function autoGrow(){const i=$('textInput');i.style.height='auto';i.style.height=Math.min(i.scrollHeight,Math.round(innerHeight*.42))+'px';updateInputState()}
function renderAttachments(){const tray=$('attachmentTray');tray.replaceChildren();if(!s.attachments.length){tray.classList.add('hidden');updateInputState();return}tray.classList.remove('hidden');s.attachments.forEach(a=>{const n=document.createElement('div');n.className='attachment-chip';if(a.preview){const im=document.createElement('img');im.src=a.preview;n.append(im)}const t=document.createElement('span');t.textContent=a.type==='video'?`${a.name} · ${a.frames}帧`:a.type==='image'?a.name:a.type==='audio'?`录音 · ${fmtSize(a.size)}`:`${a.name} · ${fmtSize(a.size)}`;const x=document.createElement('button');x.type='button';x.textContent='×';x.addEventListener('click',e=>{e.stopPropagation();s.attachments=s.attachments.filter(z=>z.id!==a.id);renderAttachments()});n.append(t,x);tray.append(n)});updateInputState()}
function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src})}
async function compressImage(file){if(file.size>MAX_IMAGE_BYTES)throw new Error(`${file.name} 超过 20MB`);const url=URL.createObjectURL(file);try{const im=await loadImage(url);const max=1600,scale=Math.min(1,max/Math.max(im.naturalWidth,im.naturalHeight)),w=Math.max(1,Math.round(im.naturalWidth*scale)),h=Math.max(1,Math.round(im.naturalHeight*scale));const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.drawImage(im,0,0,w,h);let data=c.toDataURL('image/jpeg',.82);if(data.length>2_100_000)data=c.toDataURL('image/jpeg',.68);if(data.length>2_200_000)throw new Error(`${file.name} 压缩后仍过大`);return data}finally{URL.revokeObjectURL(url)}}
function waitEvent(el,name){return new Promise((resolve,reject)=>{const ok=()=>{clean();resolve()},bad=()=>{clean();reject(new Error('媒体读取失败'))},clean=()=>{el.removeEventListener(name,ok);el.removeEventListener('error',bad)};el.addEventListener(name,ok,{once:true});el.addEventListener('error',bad,{once:true})})}
async function extractVideo(file,slots){if(file.size>MAX_VIDEO_BYTES)throw new Error(`${file.name} 超过 500MB`);const url=URL.createObjectURL(file),v=document.createElement('video');v.preload='metadata';v.muted=true;v.playsInline=true;v.src=url;try{await waitEvent(v,'loadedmetadata');if(!Number.isFinite(v.duration)||v.duration<=0)throw new Error('无法读取视频时长');if(v.duration>MAX_VIDEO_SECONDS)throw new Error(`${file.name} 超过 10 分钟`);const count=Math.max(1,Math.min(6,slots));const times=Array.from({length:count},(_,i)=>Math.max(.05,v.duration*((i+.5)/count)));const media=[];let preview='';for(const tm of times){v.currentTime=Math.min(Math.max(0,tm),Math.max(0,v.duration-.05));await waitEvent(v,'seeked');const max=1280,scale=Math.min(1,max/Math.max(v.videoWidth,v.videoHeight)),w=Math.max(1,Math.round(v.videoWidth*scale)),h=Math.max(1,Math.round(v.videoHeight*scale)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d',{alpha:false}).drawImage(v,0,0,w,h);let data=c.toDataURL('image/jpeg',.74);if(data.length>2_100_000)data=c.toDataURL('image/jpeg',.6);if(!preview)preview=data;media.push({kind:'image',name:`${file.name} @ ${tm.toFixed(1)}s`,data_url:data,source:'video_frame',frame_time:tm})}return {media,preview,duration:v.duration}}finally{v.removeAttribute('src');v.load();URL.revokeObjectURL(url)}}
function readBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const val=String(r.result||''),i=val.indexOf(',');resolve(i>=0?val.slice(i+1):val)};r.onerror=()=>reject(new Error('文件读取失败'));r.readAsDataURL(file)})}
async function addAudioFile(file){if(file.size>MAX_AUDIO_BYTES)throw new Error('录音超过 20MB');const data=await readBase64(file);s.attachments=s.attachments.filter(a=>a.type!=='audio');s.attachments.push({id:crypto.randomUUID(),type:'audio',name:file.name,size:file.size,media:[{kind:'audio',name:file.name,mime:file.type||'audio/mp4',data_b64:data}]});renderAttachments();openInput()}
async function addFiles(list){const files=[...list];if(!files.length)return;let existingImages=mediaPayload().filter(x=>x.kind==='image').length,existingFiles=s.attachments.filter(a=>a.type==='file').length,existingFileBytes=s.attachments.filter(a=>a.type==='file').reduce((n,a)=>n+a.size,0),hasVideo=s.attachments.some(a=>a.type==='video');for(const file of files){try{if(file.type.startsWith('image/')){if(existingImages>=MAX_IMAGES)throw new Error('一次最多 6 张图片/画面');toast(`处理图片 ${file.name}`,1200);const data=await compressImage(file);s.attachments.push({id:crypto.randomUUID(),type:'image',name:file.name,size:file.size,preview:data,media:[{kind:'image',name:file.name,data_url:data,source:'image'}]});existingImages++}else if(file.type.startsWith('video/')){if(hasVideo)throw new Error('一次最多 1 个视频');if(existingImages>=MAX_IMAGES)throw new Error('当前已没有视频抽帧位置');toast(`读取视频 ${file.name}`,1800);const out=await extractVideo(file,MAX_IMAGES-existingImages);s.attachments.push({id:crypto.randomUUID(),type:'video',name:file.name,size:file.size,preview:out.preview,frames:out.media.length,media:out.media});existingImages+=out.media.length;hasVideo=true}else{if(existingFiles>=MAX_FILES)throw new Error('一次最多 5 个文件');if(existingFileBytes+file.size>MAX_FILE_TOTAL)throw new Error('本轮文件总量最多 30MB');toast(`读取文件 ${file.name}`,1200);const data=await readBase64(file);s.attachments.push({id:crypto.randomUUID(),type:'file',name:file.name,size:file.size,media:[{kind:'file',name:file.name,mime:file.type||'application/octet-stream',data_b64:data}]});existingFiles++;existingFileBytes+=file.size}}catch(e){toast(e.message||'附件处理失败',3200)}}renderAttachments();openInput()}
renderSettings();autoGrow();updateInputState();
$('stage').addEventListener('click',e=>{if(s.suppressClick){s.suppressClick=false;return}if(e.target.closest?.('.attachment-chip')||e.target.closest?.('.attachment-menu')||e.target.id==='inputState'||s.recording)return;closeAttachmentMenu();openInput()});
$('textInput').addEventListener('input',autoGrow);
$('textInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();sendCurrent()}});
for(const id of ['imageInput','videoInput','fileInput']){$(id).addEventListener('change',async e=>{const files=e.target.files;closeAttachmentMenu();await addFiles(files);e.target.value=''})}
$('attachmentMenu').addEventListener('click',e=>{const b=e.target.closest?.('button[data-pick]');if(!b)return;e.stopPropagation();const map={image:'imageInput',video:'videoInput',file:'fileInput'};$(map[b.dataset.pick]).click()});
$('inputState').addEventListener('pointerup',e=>{e.preventDefault();e.stopPropagation();if(s.busy)return;if($('textInput').value.trim()||s.attachments.length){closeAttachmentMenu();sendCurrent()}else toggleAttachmentMenu()});
let touchX=0,touchY=0,holdTimer=null,holdReady=false,holdCanceled=false;function clearHold(){if(holdTimer){clearTimeout(holdTimer);holdTimer=null}}
$('stage').addEventListener('touchstart',e=>{const target=e.target;if(s.settings||s.recording||target.id==='textInput'||target.closest?.('#kButton')||target.closest?.('#inputState')||target.closest?.('.attachment-menu')||target.closest?.('.attachment-chip'))return;const t=e.touches[0];touchX=t.clientX;touchY=t.clientY;holdReady=false;holdCanceled=false;clearHold();holdTimer=setTimeout(()=>{holdReady=true;holdTimer=null},400)},{passive:true});
$('stage').addEventListener('touchmove',e=>{if(holdCanceled||holdReady)return;const t=e.touches[0],dx=t.clientX-touchX,dy=t.clientY-touchY;if(Math.hypot(dx,dy)>12){holdCanceled=true;clearHold()}},{passive:true});
$('stage').addEventListener('touchend',e=>{clearHold();const t=e.changedTouches[0],dx=t.clientX-touchX,dy=t.clientY-touchY;if(holdReady){s.suppressClick=true;if(dx>55&&Math.abs(dy)<80)openSettings()}holdReady=false;holdCanceled=false},{passive:true});$('stage').addEventListener('touchcancel',()=>{clearHold();holdReady=false;holdCanceled=false},{passive:true});
$('settings').addEventListener('touchstart',e=>{touchX=e.touches[0].clientX},{passive:true});$('settings').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchX;if(dx<-70){s.settings=false;$('settings').classList.remove('open');$('settings').setAttribute('aria-hidden','true')}},{passive:true});
$('settings').addEventListener('click',e=>{const sense=e.target.closest?.('[data-device-sense]'),install=e.target.closest?.('[data-install]'),perms=e.target.closest?.('[data-permissions]');if(sense){e.preventDefault();enableDeviceSense(false)}else if(install){e.preventDefault();showInstallHelp()}else if(perms){e.preventDefault();showPermissionStatus()}});
function overlay(kind){const o=$('captureOverlay');o.replaceChildren();o.classList.remove('hidden');if(kind==='audio'){const c=document.createElement('div');c.className='capture-center';c.innerHTML='<div class="wave">'+Array.from({length:25},()=>'<i></i>').join('')+'</div><div class="rec-label">正在录音…</div>';o.append(c)}else{const tm=document.createElement('div');tm.className='rec-time';tm.id='recTime';tm.textContent='REC 00:00';const c=document.createElement('div');c.className='capture-center';c.innerHTML='<div class="video-box"></div><div class="rec-label">正在录像…</div>';o.append(tm,c)}}
async function startCapture(video){if(s.busy||s.recording)return;try{const stream=await navigator.mediaDevices.getUserMedia(video?{audio:true,video:{facingMode:'environment'}}:{audio:true});s.permissions.microphone='granted';if(video)s.permissions.camera='granted';renderSettings();s.stream=stream;s.chunks=[];const rec=new MediaRecorder(stream);s.media=rec;rec.ondataavailable=e=>{if(e.data&&e.data.size)s.chunks.push(e.data)};rec.start(250);s.recording=true;s.video=video;s.startTime=Date.now();closeInput();$('kButton').classList.toggle('video',video);overlay(video?'video':'audio');if(video){s.timer=setInterval(()=>{const n=$('recTime');if(n){const sec=Math.floor((Date.now()-s.startTime)/1000);n.textContent='REC '+String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}},500)}}catch(e){s.permissions.microphone='denied';if(video)s.permissions.camera='denied';renderSettings();toast('需要麦克风/摄像头权限')}}
function stopCapture(){if(!s.recording)return;clearInterval(s.timer);const rec=s.media,stream=s.stream,chunks=s.chunks.slice(),wasVideo=s.video,mime=(rec&&rec.mimeType)|| (wasVideo?'video/mp4':'audio/mp4');s.recording=false;s.video=false;$('kButton').classList.remove('video');$('captureOverlay').classList.add('hidden');setBusy(true);$('progressWrap').classList.remove('hidden');if(rec){rec.onstop=async()=>{try{const blob=new Blob(chunks,{type:mime});const ext=wasVideo?(mime.includes('mp4')?'mp4':'webm'):(mime.includes('mp4')?'m4a':'webm');const file=new File([blob],`K-${wasVideo?'video':'audio'}-${Date.now()}.${ext}`,{type:mime});if(wasVideo)await addFiles([file]);else await addAudioFile(file);toast(wasVideo?'录像已加入附件':'录音已加入附件',2200)}catch(e){toast(e.message||'录制处理失败',3000)}finally{setBusy(false)}}}try{rec?.stop();stream?.getTracks().forEach(t=>t.stop())}catch(_e){setBusy(false)}}
const kb=$('kButton');kb.addEventListener('pointerdown',e=>{e.preventDefault();s.pressStart=Date.now();s.pressTimer=setTimeout(()=>{s.pressTimer=null;if(!s.recording)startCapture(true)},650)});kb.addEventListener('pointerup',e=>{e.preventDefault();if(s.pressTimer){clearTimeout(s.pressTimer);s.pressTimer=null;if(s.recording)stopCapture();else startCapture(false)}else if(s.recording&&s.video)stopCapture()});kb.addEventListener('pointercancel',()=>{if(s.pressTimer){clearTimeout(s.pressTimer);s.pressTimer=null}});
window.addEventListener('pointerup',()=>{if(localStorage.getItem('kDeviceSense')==='1'&&!s.device.enabled)enableDeviceSense(true)},{once:true,capture:true});
window.addEventListener('online',renderSettings);window.addEventListener('offline',()=>toast('当前离线；K 外壳仍可打开，聊天需恢复网络',3500));if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{}))}
